package net.ronm19.wolfism.client.model;

import net.minecraft.client.model.animal.wolf.AdultWolfModel;
import net.minecraft.client.model.geom.ModelLayerLocation;
import net.minecraft.client.model.geom.ModelPart;
import net.minecraft.client.model.geom.PartPose;
import net.minecraft.client.model.geom.builders.CubeDeformation;
import net.minecraft.client.model.geom.builders.CubeListBuilder;
import net.minecraft.client.model.geom.builders.LayerDefinition;
import net.minecraft.client.model.geom.builders.MeshDefinition;
import net.minecraft.client.model.geom.builders.PartDefinition;
import net.minecraft.resources.Identifier;
import net.ronm19.wolfism.Wolfism;

/**
 * Vanilla adult wolf body with two exactly mirrored Sculk Sensor-style tendrils.
 *
 * <p>Both sides are generated by the same method. The only difference is the
 * sign of X/roll, preventing the two tendrils from drifting into different
 * positions because of hand-copied transforms.</p>
 */
public final class SculkAdultWolfModel extends AdultWolfModel {
    public static final ModelLayerLocation LAYER_LOCATION = new ModelLayerLocation(
            Identifier.fromNamespaceAndPath(Wolfism.MOD_ID, "sculk_wolf"),
            "main");

    public SculkAdultWolfModel(ModelPart root) {
        super(root);
    }

    public static LayerDefinition createBodyLayer() {
        MeshDefinition mesh = AdultWolfModel.createBodyLayer(new CubeDeformation(0.0F));
        PartDefinition realHead = mesh.getRoot()
                .getChild("head")
                .getChild("real_head");

        addSensorTendril(realHead, "left", 1.0F);
        addSensorTendril(realHead, "right", -1.0F);

        return LayerDefinition.create(mesh, 64, 32);
    }

    /**
     * Builds one side of the sensory growth.
     *
     * @param side +1 for left, -1 for right.
     */
    private static void addSensorTendril(
            PartDefinition realHead,
            String name,
            float side) {

        /*
         * IMPORTANT:
         * - Same Y and Z for both sides.
         * - Same lengths for both sides.
         * - Same pitch for both sides.
         * - Only X position and Z-axis bend are mirrored.
         *
         * This guarantees exact bilateral placement.
         */

        PartDefinition root = realHead.addOrReplaceChild(
                name + "_sculk_tendril_root",
                CubeListBuilder.create()
                        .texOffs(0, 0)
                        .addBox(
                                -0.45F, -1.45F, -0.45F,
                                0.90F, 1.50F, 0.90F,
                                new CubeDeformation(0.015F)),
                PartPose.offsetAndRotation(
                        2.55F * side,
                        -2.35F,
                        1.45F,
                        -0.08F,
                        0.0F,
                        -0.42F * side));

        PartDefinition middle = root.addOrReplaceChild(
                name + "_sculk_tendril_middle",
                CubeListBuilder.create()
                        .texOffs(24, 0)
                        .addBox(
                                -0.38F, -1.55F, -0.38F,
                                0.76F, 1.60F, 0.76F,
                                new CubeDeformation(0.01F)),
                PartPose.offsetAndRotation(
                        0.0F,
                        -1.34F,
                        0.0F,
                        -0.05F,
                        0.0F,
                        -0.28F * side));

        PartDefinition upper = middle.addOrReplaceChild(
                name + "_sculk_tendril_upper",
                CubeListBuilder.create()
                        .texOffs(44, 0)
                        .addBox(
                                -0.32F, -1.30F, -0.32F,
                                0.64F, 1.35F, 0.64F,
                                new CubeDeformation(0.005F)),
                PartPose.offsetAndRotation(
                        0.0F,
                        -1.43F,
                        0.0F,
                        0.03F,
                        0.0F,
                        0.60F * side));

        upper.addOrReplaceChild(
                name + "_sculk_tendril_tip",
                CubeListBuilder.create()
                        .texOffs(46, 0)
                        .addBox(
                                -0.27F, -0.95F, -0.27F,
                                0.54F, 1.00F, 0.54F,
                                new CubeDeformation(0.0F)),
                PartPose.offsetAndRotation(
                        0.0F,
                        -1.18F,
                        0.0F,
                        0.02F,
                        0.0F,
                        -0.32F * side));

        middle.addOrReplaceChild(
                name + "_sculk_tendril_fork",
                CubeListBuilder.create()
                        .texOffs(45, 2)
                        .addBox(
                                -0.27F, -0.98F, -0.27F,
                                0.54F, 1.03F, 0.54F,
                                new CubeDeformation(0.0F)),
                PartPose.offsetAndRotation(
                        0.30F * side,
                        -1.12F,
                        0.0F,
                        -0.03F,
                        0.0F,
                        -0.78F * side));
    }
}