package net.ronm19.wolfism.registry;

import net.minecraft.core.Holder;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.sounds.SoundEvent;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.neoforge.registries.DeferredRegister;
import net.ronm19.wolfism.Wolfism;

/**
 * Central sound-event registry for Wolfism.
 *
 * <p>The SOUND EVENT is registered here. The mapping from that event to one or
 * more .ogg files is generated by ModSoundDefinitionsProvider into
 * assets/wolfism/sounds.json.</p>
 *
 * <p>When more wolves receive custom audio, keep adding their events here
 * instead of manually writing sounds.json entries.</p>
 */
public final class ModSounds {

    public static final DeferredRegister<SoundEvent> SOUND_EVENTS =
            DeferredRegister.create(
                    BuiltInRegistries.SOUND_EVENT,
                    Wolfism.MOD_ID);

    // ---------------------------------------------------------------------
    // Wolf King
    // ---------------------------------------------------------------------

    public static final Holder<SoundEvent> WOLF_KING_HOWL = registerVariable("entity.wolf_king.howl");

    // ---------------------------------------------------------------------
    // Primordial Wolf
    // ---------------------------------------------------------------------

    public static final Holder<SoundEvent> PRIMORDIAL_WOLF_HOWL =
            registerVariable("entity.primordial_wolf.howl");

    // ---------------------------------------------------------------------
    // Creator Wolf — audio hooks; actual .ogg assets come after gameplay.
    // ---------------------------------------------------------------------

    public static final Holder<SoundEvent> CREATOR_WOLF_HOWL =
            registerVariable("entity.creator_wolf.howl");
    public static final Holder<SoundEvent> CREATOR_WOLF_GROWL =
            registerVariable("entity.creator_wolf.growl");



    // ---------------------------------------------------------------------
    // Future 53-wolf audio
    // ---------------------------------------------------------------------
    //
    // Example:
    //
    // public static final Holder<SoundEvent> TIMBER_AMBIENT =
    //         registerVariable("entity.timber_wolf.ambient");
    //
    // public static final Holder<SoundEvent> TIMBER_HURT =
    //         registerVariable("entity.timber_wolf.hurt");
    //
    // public static final Holder<SoundEvent> TIMBER_DEATH =
    //         registerVariable("entity.timber_wolf.death");
    //
    // You only register the event here ONCE.
    // File variants belong in ModSoundDefinitionsProvider.

    private static Holder<SoundEvent> registerVariable( String path) {
        return SOUND_EVENTS.register(path, SoundEvent::createVariableRangeEvent);
    }

    public static void register(IEventBus modEventBus) {
        SOUND_EVENTS.register(modEventBus);
    }

    private ModSounds() {
    }
}
